[theme]
# .streamlit/config.toml

# Cor de fundo principal do aplicativo
primaryColor="#8A2BE2" # Roxo

# Cor do fundo geral
backgroundColor="#FAFAFA" # Quase preto

# Cor de fundo da barra lateral e outros elementos secundários
secondaryBackgroundColor="#FAFAFA" 

# Cor do texto principal
textColor="#262730" 

# Cor da fonte para widgets, etc.
font="sans serif"